<script setup>
import Dialog from '@/components/Dialog.vue'
const chat = [
    {
        cg:'./map/bg/1.jpg',
        msg:'(脚步声)哒哒哒...'
    },{
        cg:'./map/bg/1.jpg',
        stand:{
            head:'0',
            late_hair:'0',
            face:'0',
            cheek:'',
            body:'0',
            clothes:'0',
        },
        name:'少女',
        highlight:'a',
        msg:'你好,我是尤娜',
        animate:'fadeIn',
        objAnimate:'',
    },{
        cg:'./map/bg/1.jpg',
        stand:{
            head:'0',
            late_hair:'0',
            face:'0',
            cheek:'',
            body:'0',
            clothes:'0',
        },
        name:'尤娜',
        highlight:'a',
        msg:'这是一款以js开发的RPG游戏,目前还在开发状态...',
    },{
        cg:'./map/bg/1.jpg',
        stand:{
            head:'0',
            late_hair:'0',
            face:'0',
            cheek:'',
            body:'0',
            clothes:'0',
        },
        name:'尤娜',
        highlight:'a',
        msg:'这款游戏可以在电脑,手机端都可以玩.讲述了女孩尤娜的冒险生活...',
        objAnimate:'',
    },{
        cg:'./map/bg/1.jpg',
        stand:{
            head:'0',
            late_hair:'0',
            face:'1',
            cheek:'',
            body:'0',
            clothes:'0',
        },
        name:'尤娜',
        highlight:'a',
        msg:'啊啊啊啊!!!怎么文案这么长啊!!!',
        animate:'heartBeat',
    },{
        cg:'./map/bg/1.jpg',
        stand:{
            head:'0',
            late_hair:'0',
            face:'1',
            cheek:'',
            body:'0',
            clothes:'0',
        },
        name:'尤娜',
        highlight:'a',
        msg:'总之就是这样!!',
        animate:'',
    },{
        cg:'./map/bg/1.jpg',
        stand:{
            head:'0',
            late_hair:'0',
            face:'0',
            cheek:'',
            body:'0',
            clothes:'0',
        },
        name:'尤娜',
        highlight:'a',
        msg:'现在游戏非常希望有伙伴能够参与一起开发',
        animate:'',
    },{
        cg:'./map/bg/1.jpg',
        stand:{
            head:'0',
            late_hair:'0',
            face:'0',
            cheek:'',
            body:'0',
            clothes:'0',
        },
        name:'尤娜',
        highlight:'a',
        msg:'无论你是否拥有编程技能,都可以参与进来。我们会有剧本编辑器,通过简单的选择,即可生成游戏剧本对话和事件',
    },{
        cg:'./map/bg/1.jpg',
        stand:{
            head:'0',
            late_hair:'0',
            face:'0',
            cheek:'',
            body:'0',
            clothes:'0',
        },
        name:'尤娜',
        highlight:'a',
        msg:'如果你对此感兴趣,可以加入QQ群207227268',
    },{
        cg:'./map/bg/1.jpg',
        stand:{
            head:'0',
            late_hair:'0',
            face:'0',
            cheek:'',
            body:'0',
            clothes:'0',
        },
        name:'尤娜',
        highlight:'a',
        msg:'就这样~再见~',
        animate:'fadeOutRight',
    },{
        cg:'./map/bg/1.jpg',
        msg:'敬请期待',
    }
]
</script>
<template>
    <div class="canvas animated fadeIn">
        <Dialog :chat="chat"></Dialog>
    </div>
</template>
<style>
.canvas{
    margin: 0 auto;
    width: 100%;
    max-width: 900px;
    height: 100%;
    max-height: 500px;
    background-color: black;
    color: #fff;
}
</style>
